FROM zenika/alpine-chrome:89-with-chromedriver
LABEL maintainer="eiriksm <eirik@nymedia.no>"
USER root

ENTRYPOINT ["chromedriver",  "--port=8643", "--url-base=wd/hub", "--headless", "--no-sandbox", "--whitelisted-ips="]
EXPOSE 8643
