
name: Build Docker Container
on:
  push:
    branches: ['*']
      # - main

env:
  REGISTRY: docker.io
  BUILD_PLATFORMS: linux/amd64,linux/arm64
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chromium_version:
          - 'latest'
          - '89'
        build_variant: # Ref: https://github.com/Zenika/alpine-chrome
          - ''
          - '-with-chromedriver'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ matrix.chromium_version }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            BASE_IMAGE_TAG=${{ matrix.chromium_version }}${{ matrix.build_variant }}
          platforms: ${{ env.BUILD_PLATFORMS }}
          push: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
